version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ~/.kube/config:/root/.kube/config:ro
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

